# Generated by Django 5.2.4 on 2025-07-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('contact', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
    ]
